version: "3"
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    networks:
      - laravel-net
    depends_on:
      - db-laravel
    # command:
    #   [
    #     "./wait-for-mysql.sh",
    #     "db-laravel",
    #     "php",
    #     "artisan",
    #     "migrate",
    #     "--force",
    #   ]
  db-laravel:
    image: mysql:5.7
    container_name: db-laravel
    environment:
      - MYSQL_DATABASE=sistem_penggajian
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=penggajian_admin
      - MYSQL_PASSWORD=Penggajian123!!!
      - SERVICE_NAME=mysql
    tty: true
    ports:
      - 3306:3306
    networks:
      - laravel-net
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
