version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - laravel-net
    environment:
      - SERVICE_NAME=app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_DATABASE=sistem_penggajian
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=penggajian_admin
      - MYSQL_PASSWORD=Penggajian123!!!
      - SERVICE_NAME=mysql
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 3306:3306
    networks:
      - laravel-net
  webserver:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx:latest
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/sistem-penggajian
      - ./config/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-net
    depends_on:
      - db
      - app

networks:
  laravel-net:
    driver: bridge
